title: Leonardo Stabile
description: >
  <strong>Data Analyst | Data Scientist</strong><br>
  Python • SQL • Power BI • Machine Learning<br><br>
  <a href="https://www.linkedin.com/in/SEU-LINK-AQUI" target="_blank">
    <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linkedin/linkedin-original.svg"
         width="18" style="vertical-align:middle; margin-right:6px;">
    LinkedIn
  </a>
theme: jekyll-theme-minimal
show_downloads: false
github:
  is_project_page: false

